default:
  gnn: 'SAGE'
  seed: [0, 1, 2, 3, 4]
  epochs: 300
  valid_epoch: 10
  lr: 1e-4
  weight_decay: 5e-4
  layer_num: 2
  hidden_dim: 128
  dropout: 0.5
  patience: 20
  batch_size: 256
  num_heads: 4 # only available for GATConv
  aggr: 'mean' # ['mean', 'max', 'lstm'], only available for SAGEConv
search_space:
  gnn: ['GCN', 'SAGE']
  lr: [1e-5, 1e-4, 1e-3]
  hidden_dim: [64, 128]
best_cora:
  gnn: GCN
  lr: '1e-5'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-03T12:39:21.910312'
    metrics:
      Iso. Avg ACC: '0.5810'
      Iso. Avg FGT: '-0.4895'
      Jot. Avg ACC: '0.6319'
      Jot. Last ACC: '0.4868'
best_citeseer:
  gnn: GAT
  lr: '1e-5'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-03T13:08:35.592951'
    metrics:
      Iso. Avg ACC: '0.4329'
      Iso. Avg FGT: '-0.5770'
      Jot. Avg ACC: '0.6045'
      Jot. Last ACC: '0.4079'
best_wikics:
  gnn: GCN
  lr: '1e-5'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-03T14:27:17.817187'
    metrics:
      Iso. Avg ACC: '0.1867'
      Iso. Avg FGT: '-0.9373'
      Jot. Avg ACC: '0.5209'
      Jot. Last ACC: '0.1503'
