default:
  gnn: 'GCN'
  seed: [0, 1, 2, 3, 4]
  epochs: 300
  valid_epoch: 10
  lr: 1e-4
  weight_decay: 5e-4
  layer_num: 2
  hidden_dim: 128
  dropout: 0.5
  patience: 20
  batch_size: 256
  num_heads: 4 # only available for GATConv
  aggr: 'mean' # ['mean', 'max', 'lstm'], only available for SAGEConv
search_space:
  gnn: ['GCN', 'SAGE']
  lr: [1e-5, 1e-4, 1e-3]
  hidden_dim: [64, 128]
best_cora:
  gnn: GCN
  lr: '1e-5'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-21T17:18:31.653381'
    metrics:
      Iso. Avg ACC: '0.4275'
      Iso. Avg FGT: '-0.4275'
      Jot. Avg ACC: '0.5738'
      Jot. Last ACC: '0.4164'
best_citeseer:
  gnn: GCN
  lr: '1e-5'
  hidden_dim: 128
  _meta:
    updated_at: '2025-04-21T17:20:15.684467'
    metrics:
      Iso. Avg ACC: '0.3355'
      Iso. Avg FGT: '-0.7825'
      Jot. Avg ACC: '0.5214'
      Jot. Last ACC: '0.3092'
best_wikics:
  gnn: GCN
  lr: '1e-5'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-21T19:48:42.695555'
    metrics:
      Iso. Avg ACC: '0.3935'
      Iso. Avg FGT: '-0.7517'
      Jot. Avg ACC: '0.5514'
      Jot. Last ACC: '0.3450'
best_photo:
  gnn: GCN
  lr: '1e-4'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-21T20:10:09.721085'
    metrics:
      Iso. Avg ACC: '0.2389'
      Iso. Avg FGT: '-0.9272'
      Jot. Avg ACC: '0.4683'
      Jot. Last ACC: '0.2065'
best_products:
  gnn: GCN
  lr: '1e-5'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-21T20:51:33.785080'
    metrics:
      Iso. Avg ACC: '0.0750'
      Iso. Avg FGT: '-0.4235'
      Jot. Avg ACC: '0.2395'
      Jot. Last ACC: '0.0764'
best_arxiv_23:
  gnn: GCN
  lr: '1e-5'
  hidden_dim: 64
  _meta:
    updated_at: '2025-04-21T21:20:47.075095'
    metrics:
      Iso. Avg ACC: '0.0651'
      Iso. Avg FGT: '-0.5431'
      Jot. Avg ACC: '0.1952'
      Jot. Last ACC: '0.0192'
