default:
  gnn: 'SGC'
  seed: [0, 1, 2, 3, 4]
  epochs: 300
  valid_epoch: 10
  lr: 1e-4
  weight_decay: 5e-4
  layer_num: 2
  hidden_dim: 128
  dropout: 0.5
  patience: 20
  batch_size: 200
  num_heads: 4 # only available for GATConv
  aggr: 'mean' # ['mean', 'max', 'lstm'], only available for SAGEConv

  delome_budget: 60
  delome_tro: 1.0
  delome_epochs: 900
  delome_batch_size: 2000
  delome_feat_lr: 1e-4
  delome_layer_size: [10, 25] # [15] / [10, 25] / [15, 10, 5]
search_space:
  lr: [1e-5, 1e-4, 1e-3]
  hidden_dim: [128, 256]
  delome_feat_lr: [1e-5, 1e-4]
