default:
  gnn: 'GCN'
  seed: [0, 1, 2, 3, 4]
  epochs: 300
  valid_epoch: 10
  lr: 1e-4
  weight_decay: 5e-4
  layer_num: 2
  hidden_dim: 128
  dropout: 0.5
  patience: 20
  batch_size: 200
  num_heads: 4 # only available for GATConv
  aggr: 'mean' # ['mean', 'max', 'lstm'], only available for SAGEConv

  ewc_strength: 10000
search_space:
  gnn: ['GCN', 'SAGE']
  lr: [1e-5, 1e-4, 1e-3]
  ewc_strength: [1, 100, 10000]
best_cora:
  gnn: GCN
  lr: '1e-5'
  ewc_strength: 10000
  _meta:
    updated_at: '2025-04-24T08:13:24.492887'
    metrics:
      Iso. Avg ACC: '0.4022'
      Iso. Avg FGT: '-0.6467'
      Jot. Avg ACC: '0.5715'
      Jot. Last ACC: '0.3486'
best_citeseer:
  gnn: GCN
  lr: '1e-3'
  ewc_strength: 1
  _meta:
    updated_at: '2025-04-24T08:15:02.695754'
    metrics:
      Iso. Avg ACC: '0.2083'
      Iso. Avg FGT: '-0.7100'
      Jot. Avg ACC: '0.4436'
      Jot. Last ACC: '0.2133'
best_wikics:
  gnn: GCN
  lr: '1e-5'
  ewc_strength: 10000
  _meta:
    updated_at: '2025-04-24T08:21:20.748186'
    metrics:
      Iso. Avg ACC: '0.4487'
      Iso. Avg FGT: '-0.6167'
      Jot. Avg ACC: '0.6189'
      Jot. Last ACC: '0.3925'
best_photo:
  gnn: GCN
  lr: '1e-5'
  ewc_strength: 10000
  _meta:
    updated_at: '2025-04-24T08:46:50.366234'
    metrics:
      Iso. Avg ACC: '0.3471'
      Iso. Avg FGT: '-0.6603'
      Jot. Avg ACC: '0.6162'
      Jot. Last ACC: '0.3102'
best_products:
  gnn: GCN
  lr: '1e-5'
  ewc_strength: 10000
  _meta:
    updated_at: '2025-04-24T09:06:38.611403'
    metrics:
      Iso. Avg ACC: '0.1240'
      Iso. Avg FGT: '-0.0654'
      Jot. Avg ACC: '0.4604'
      Jot. Last ACC: '0.3464'
best_arxiv_23:
  gnn: GCN
  lr: '1e-5'
  ewc_strength: 10000
  _meta:
    updated_at: '2025-04-24T09:27:56.666038'
    metrics:
      Iso. Avg ACC: '0.0892'
      Iso. Avg FGT: '-0.0412'
      Jot. Avg ACC: '0.3737'
      Jot. Last ACC: '0.2992'
best_arxiv:
  gnn: GCN
  lr: '1e-5'
  ewc_strength: 10000
  _meta:
    updated_at: '2025-05-04T20:17:21.797576'
    metrics:
      Iso. Avg ACC: '0.0374'
      Iso. Avg FGT: '-0.4889'
      Jot. Avg ACC: '0.1576'
      Jot. Last ACC: '0.0437'
