default:
  gnn: 'GCN'
  seed: [0, 1, 2, 3, 4]
  epochs: 300
  valid_epoch: 10
  lr: 1e-4
  weight_decay: 5e-4
  layer_num: 2
  hidden_dim: 128
  dropout: 0.5
  patience: 20
  batch_size: 200
  num_heads: 4 # only available for GATConv
  aggr: 'mean' # ['mean', 'max', 'lstm'], only available for SAGEConv

  tpp_prompts: 3

  tpp_grace_pe: 0.2
  tpp_grace_pf: 0.3
  tpp_grace_epochs: 500
  tpp_grace_lr: 1e-3
  tpp_grace_batch_size: 500
search_space:
  gnn: ['GCN', 'SAGE']
  lr: [1e-4, 1e-3]
  tpp_grace_pe: [0.2, 0.3]
  tpp_grace_pf: [0.2, 0.3]