default:
  lm: 'LLaMA' # ['RoBERTa', 'LLaMA']
  seed: [0, 1, 2, 3, 4]
  epochs: 2
  valid_epoch: 1
  warmup_epochs: 1
  lr: 2e-4
  min_lr: 5e-6
  grad_steps: 2
  weight_decay: 5e-2
  dropout: 0.1
  att_dropout: 0.1
  patience: 5
  batch_size: 10
  max_length: 256
  LoRA:
    use_lora: True
    lora_r: 5
    lora_alpha: 16
    lora_dropout: 0.05

  simplecil_T: 1.0
  simplecil_sample_num: 20
search_space:
  lr: [1e-4, 2e-4, 5e-4]